# Generated by Django 5.1.1 on 2024-10-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topsis_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topsisanalysis",
            name="input_file",
            field=models.CharField(max_length=400),
        ),
    ]
